POST http://{{ip}}:{{port}}/v1/user/create
Content-Type: application/json

{
  "name": "Nome do Usuário",
  "cpf": "009.326.838-60",
  "phone": "11940055071",
  "birthday": "2000-01-01"
}

> {%
    client.global.set("id", response.body.id);
    client.global.set("cpf", response.body.cpf);
%}

###

GET http://{{ip}}:{{port}}/v1/user/
Accept: application/json

###
GET http://{{ip}}:{{port}}/v1/user/cpf/{{cpf}}

###
GET http://{{ip}}:{{port}}/v1/user/{{id}}

###
PUT http://{{ip}}:{{port}}/v1/user/{{id}}
Content-Type: application/json

{
  "name": "Diogo Henrique Barbosa"
}

###
DELETE http://{{ip}}:{{port}}/v1/user/{{id}}}
